### ISSUE TITLE
Trying to start controller, I get a SyntaxError: duplicate argument 'self' in function definition error

### ISSUE THREAD

**Issue by diarmuidcire** [wishful-project/framework#3]
I get the following SyntaxError: duplicate argument 'self' in function definition when trying to start the controller. 

I get it in GNU Radio, but also Iris. Can someone investigate?

(dev) nodeuser@experiment-unit:~/examples/gnuradio$ ./wishful_simple_controller --config ./controller_config.yaml 
Traceback (most recent call last):
  File "./wishful_simple_controller", line 24, in <module>
    controller = wishful_controller.Controller(dl="tcp://127.0.0.1:8990", ul="tcp://127.0.0.1:8989")
  File "/home/nodeuser/dev/lib/python3.5/site-packages/wishful_controller/controller.py", line 122, in __init__
    self.radio = builder.create_radio()
  File "/home/nodeuser/dev/lib/python3.5/site-packages/wishful_framework/controller/upis_builder.py", line 141, in create_radio
    function = self.perpare_function(method, function)
  File "/home/nodeuser/dev/lib/python3.5/site-packages/wishful_framework/controller/upis_builder.py", line 117, in perpare_function
    function = compile(code, 'My_Code', 'exec')
  File "My_Code", line 1
SyntaxError: duplicate argument 'self' in function definition
(dev) nodeuser@experiment-unit:~/examples/gnuradio$ 

(dev) nodeuser@experiment-unit:~/examples/iris$ ./wishful_simple_controller --config ./controller_config.yaml 
Traceback (most recent call last):
  File "./wishful_simple_controller", line 39, in <module>
    controller = wishful_controller.Controller()
  File "/home/nodeuser/dev/lib/python3.5/site-packages/wishful_controller/controller.py", line 122, in __init__
    self.radio = builder.create_radio()
  File "/home/nodeuser/dev/lib/python3.5/site-packages/wishful_framework/controller/upis_builder.py", line 141, in create_radio
    function = self.perpare_function(method, function)
  File "/home/nodeuser/dev/lib/python3.5/site-packages/wishful_framework/controller/upis_builder.py", line 117, in perpare_function
    function = compile(code, 'My_Code', 'exec')
  File "My_Code", line 1
SyntaxError: duplicate argument 'self' in function definition

**Comment by pruckebusch** [comment]
Hey,

this error occurs when you mix wishful 2.1/3 UPI specifications (dev branch) and the master branch of WiSHFUL 2.0 framework repo. In the 2.1/3 UPI specifications, the UPIs are grouped in python classes, hence the self argument is present in the UPI function signature. In the 2.0 version of the framework repo (master branch), upi_builder adds self to the argument list in perpare_function.

The only "fix" for this issue is to not mix dev and master branches of the different repositories.
